//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinanciamiento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deuda
    {
        public int IDDeuda { get; set; }
        public string NDeuda { get; set; }
        public System.DateTime FechaInicioDeuda { get; set; }
        public System.DateTime FechaFinDeuda { get; set; }
        public string TDescripcion { get; set; }
        public Nullable<float> Interes { get; set; }
        public decimal MontoDeuda { get; set; }
        public int IDDivisa { get; set; }
        public int IDCategoria_Deuda { get; set; }
        public int IDEntidad { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Categoria_Deuda Categoria_Deuda { get; set; }
        public virtual Divisa Divisa { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
