// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC2.Repository.Context;

namespace PC2.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191119002510_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PC2.Domain.Planta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DiaEmision");

                    b.Property<DateTime>("DiaPago");

                    b.Property<int>("NroFactura");

                    b.Property<float>("Retencion");

                    b.Property<float>("TotalFacturado");

                    b.Property<int>("moneda");

                    b.HasKey("id");

                    b.ToTable("Plantas");
                });

            modelBuilder.Entity("PC2.Domain.Planta_Vivero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fechaRegistro");

                    b.Property<int?>("plantaid");

                    b.Property<int?>("viveroid");

                    b.HasKey("id");

                    b.HasIndex("plantaid");

                    b.HasIndex("viveroid");

                    b.ToTable("Plantas_Viveros");
                });

            modelBuilder.Entity("PC2.Domain.Vivero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CostoFinal");

                    b.Property<float>("CostoInicial");

                    b.Property<float>("Descuento");

                    b.Property<float>("TCEA");

                    b.Property<float>("TsDescontada");

                    b.Property<float>("TsEfectiva");

                    b.Property<float>("ValorEntero");

                    b.Property<float>("ValorNeto");

                    b.Property<float>("ValorRecaudado");

                    b.Property<string>("nombre");

                    b.HasKey("id");

                    b.ToTable("Viveros");
                });

            modelBuilder.Entity("PC2.Domain.Planta_Vivero", b =>
                {
                    b.HasOne("PC2.Domain.Planta", "planta")
                        .WithMany()
                        .HasForeignKey("plantaid");

                    b.HasOne("PC2.Domain.Vivero", "vivero")
                        .WithMany()
                        .HasForeignKey("viveroid");
                });
#pragma warning restore 612, 618
        }
    }
}
